DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP TABLE REVIEW;
DROP TABLE REPLY;
DROP TABLE REPLY_RE;
DROP TABLE COMMENT1;
DROP TABLE NOVEL;
DROP TABLE LLIKE;
DROP TABLE OPINION;


SELECT * FROM USER_TABLES;
SELECT * FROM NOVEL;

CREATE TABLE MEMBER(
   MID VARCHAR(20) PRIMARY KEY,
   MPW VARCHAR(20) NOT NULL,
   MNAME VARCHAR(20) NOT NULL,
   NICKNAME VARCHAR(20) NOT NULL,
   MPHONE VARCHAR(20) NOT NULL,
   MEMAIL VARCHAR(50) NOT NULL,
   ROLE VARCHAR(20) NOT NULL
)

-- RIVIEW -> OPINION으로 수정
CREATE TABLE OPINION(
   OID INT PRIMARY KEY,
   OCONTENT VARCHAR(500) NOT NULL,
   ODATE  DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   LID INT NOT NULL,
   OSTAR INT NOT NULL
)

CREATE TABLE BOARD(
   BID INT PRIMARY KEY,
   BTITLE VARCHAR(50) NOT NULL,
   BCONTENT VARCHAR(1000) NOT NULL,
   BDATE DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   LID INT NOT NULL
)


-- COMMENT 이름으로 테이블 생성 불가, 댓글 REPLY로 수정
CREATE TABLE REPLY(
   RID INT PRIMARY KEY,
   RCONTENT VARCHAR(1000) NOT NULL,
   RDATE DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   LID INT NOT NULL,
   BID INT NOT NULL,
   CONSTRAINT BOARD_REPLY FOREIGN KEY (BID) REFERENCES BOARD(BID) ON DELETE CASCADE
);

-- 대댓글 REPLY_RE 로 수정
CREATE TABLE REPLY_RE(
   RRID INT PRIMARY KEY,
   RRCONTENT VARCHAR(1000) NOT NULL,
   RRDATE  DATE DEFAULT SYSDATE,
   MID VARCHAR(20) NOT NULL,
   LID INT NOT NULL,
   BID INT NOT NULL,
   RID INT NOT NULL,
   CONSTRAINT REPLY_REPLY_RE FOREIGN KEY (RID) REFERENCES REPLY(RID) ON DELETE CASCADE
)


CREATE TABLE NOVEL(
   NID INT PRIMARY KEY,
   NTITLE VARCHAR(70) NOT NULL,
   NCONTENT VARCHAR(1000) NOT NULL,
   NIMG VARCHAR(2000) NOT NULL,
   NGENRE VARCHAR(60) NOT NULL,
   NWRITER VARCHAR(30) NOT NULL,
   OID INT NOT NULL
)

-- LIKE가 키워드라 테이블 생성 불가, LLIKE로 생성
CREATE TABLE LLIKE(
   LID INT PRIMARY KEY,
   MID VARCHAR(20) NOT NULL,
   RID INT NOT NULL,
   BID INT NOT NULL,
   LSTATUS INT DEFAULT 0,
   NLSTATUS INT DEFAULT 0,
   REPORT INT DEFAULT 0,
   CONSTRAINT BOARD_LLIKE FOREIGN KEY (BID) REFERENCES BOARD(BID) ON DELETE CASCADE
);


SELECT * FROM (SELECT * FROM BOARD LEFT OUTER JOIN MEMBER ON BOARD.MID=MEMBER.NICKNAME ORDER BY BID DESC) WHERE ROWNUM < = ?
SELECT * FROM (SELECT * FROM NOVEL WHERE NTITLE LIKE '%'||?||'%' AND NGENRE LIKE '%'||?||'%' AND NWRITER LIKE '%'||?||'%' ORDER BY NID DESC) WHERE ROWNUM < = ?

